spring.application.name=accreditation-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/adfads
spring.datasource.username=postgres
spring.datasource.password=adfdf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

aws.region=fdasfasdf
aws.s3.bucket-name=adfdsaf