spring.application.name=accreditation-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/accreditation_db
spring.datasource.username=usernameniggaa
spring.datasource.password=passwordniggaaa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 